package com.reactnativejitsimeetsdk;

public class Constants {

  public static final String CONST_JS_CONFERENCE_JOINED_EVENT_NAME = "CONFERENCE_JOINED_EVENT_NAME";
  public static final String CONST_JS_CONFERENCE_WILL_JOIN_EVENT_NAME = "CONFERENCE_WILL_JOIN_EVENT_NAME";
  public static final String CONST_JS_CONFERENCE_TERMINATED_EVENT_NAME = "CONFERENCE_TERMINATED_EVENT_NAME";
  public static final String CONST_JS_PARTICIPANT_LEFT_EVENT_NAME = "PARTICIPANT_LEFT_EVENT_NAME";
  public static final String CONST_JS_PARTICIPANT_JOINED_EVENT_NAME = "PARTICIPANT_JOINED_EVENT_NAME";
  public static final String CONST_JS_RETRIEVE_PARTICIPANT_INFO_EVENT_NAME = "RETRIEVE_PARTICIPANT_INFO_EVENT_NAME";

  public static final String RETRIEVE_INTENT = "org.jitsi.meet.RETRIEVE_PARTICIPANTS_INFO";
}
